### ISSUE TITLE
[✅ FEAT] 회원가입

### ISSUE THREAD

**Issue by mint3382** [DiaryVoteTemp/PMC_iOS#1]
## 📚 TASK
- 회원가입 시 입력해야 하는 페이지들 구현
- API 연결 X

## ✅ TODO
- [x] 닉네임 페이지
- [x] 휴대폰, 이메일 페이지
- [x] 아이디, 비밀번호 페이지
- [x] 약관 동의 페이지
